### ISSUE TITLE
[Feature Request]Pass props to layout component

### ISSUE THREAD

**Issue by yaquawa** [JohnCampionJr/vite-plugin-vue-layouts#12]
It'll be more flexible if we can pass any props to the layout component.

For example:
`page.vue`
```yaml
<route lang="yaml">
meta:
  layout: users
  layoutProps: 
      showMenu: true
      hideBreadcrumb: false
</route>
```

`layout.vue`
```vue
<template>
  <div v-if='showMenu'>...</div>
  <div v-if='hideBreadcrumb'>...</div>
</template>

<script>
export default {
  props: {
    showMenu: Boolean,
    hideBreadcrumb: Boolean
  }
}
</script>
```
or add a `useLayout` api could even get more flexibility.
